---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pebble-config
data:
  pebble-config.json: |
    {
      "pebble": {
        "listenAddress": "0.0.0.0:30100",
        "managementListenAddress": "0.0.0.0:30200",
        "certificate": "/tls/tls.crt",
        "privateKey": "/tls/tls.key",
        "httpPort": 30501,
        "tlsPort": 30502,
        "ocspResponderURL": "",
        "externalAccountBindingRequired": false,
        "domainBlocklist": [
          "blocked-domain.example"
        ],
        "retryAfter": {
          "authz": 3,
          "order": 5
        },
        "certificateValidityPeriod": 157766400
      }
    }