
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pebble
  labels:
    name: pebble
  namespace: pebble
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pebble
  template:
    metadata:
      labels:
        name: pebble
    spec:
      containers:
        - name: pebble
          image: quay.io/powercloud/pebble-tool:pebble
          imagePullPolicy: Always
          command: [ "/usr/bin/pebble" ]
          args: [ "-config", "/config/pebble-config.json" ]
          env:
          - name: PEBBLE_VA_NOSLEEP
            value: "1"
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 30100
            - containerPort: 30200
            - containerPort: 30501
            - containerPort: 30502
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: pebble-vol
              mountPath: /tmp
            - name: pebble-config
              mountPath: "/config"
              readOnly: true
            - name: pebble-tls
              mountPath: "/tls"
              readOnly: true
      volumes:
        - name: pebble-vol
          emptyDir:
            medium: Memory
        - name: pebble-config
          configMap:
            name: pebble-config
            items:
            - key: "pebble-config.json"
              path: "pebble-config.json"
        - name: pebble-tls
          secret: 
            secretName: pebble-tls
      nodeSelector:
        node.openshift.io/os_id: rhcos
        kubernetes.io/arch: ppc64le
---
apiVersion: v1
kind: Service
metadata:
  name: pebble-svc
  labels:
    name: pebble
spec:
  type: NodePort
  ports:
  - port: 30100
    name: pebble4
    protocol: TCP
    targetPort: 30100
    nodePort: 30100
  - port: 30200
    name: pebble5
    protocol: TCP
    targetPort: 30200
    nodePort: 30200
  - port: 30501
    name: pebblehttp
    protocol: TCP
    targetPort: 30501
    nodePort: 30501
  - port: 30502
    name: pebblehttps
    protocol: TCP
    targetPort: 30502
    nodePort: 30502
  selector:
    name: pebble